name: Manual1
on:
  workflow_dispatch:
    inputs:
      log-level:
        type: choice
        options:
          - info
          - warn
          - error

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Log level is ${{ inputs.log-level }}"
